### ISSUE TITLE
GluonNLP 0.4 release tasks

### ISSUE THREAD

**Issue by szha** [dmlc/gluon-nlp#271]
We're targeting GluonNLP 0.4 release on 8/17 in preparation for the upcoming KDD tutorials. 
@sxjscience @szhengac @leezu 
@cgraywang @astonzhang @eric-haibin-lin 
@piiswrong @mli 

Here's the proposed scope. Please comment if you'd like to add or drop any item:
- [ ] #279 (@cgraywang)
- [ ] #199 #170 (@cgraywang)
- [ ] new language model parameters on wikitext2 (@cgraywang)
- [x] #298 #299 (@cgraywang @szha)
- [x] Verify machine translation scripts and examples (@sxjscience @szhengac)
- [x] #285 (@szhengac)
- [x] #294 (@eric-haibin-lin)
- [x] #274 #280 (@szhengac)
- [x] #233 (@junrushao1994)
- [x] #245 #246 (@leezu)
- [x] Verify language model scripts and examples (@cgraywang, @eric-haibin-lin, @leezu)
- [x] Verify embedding scripts and examples (@leezu)
- [x] #245 #128 #282 (@leezu)
  - [x]  #291 (@leezu)
- [x] #262 #270 (@eric-haibin-lin)
- [x] #277 #278 (@eric-haibin-lin)
- [x] Update contributors list (@szha)
- [x] #264 #268 (@szha)
- [x] #205 #293 (@szha)
- [x] Sampler in #172 (@hhexiy @szha)

To our contributors: if you have work you'd like to get into GluonNLP 0.4 and you can commit to finish by 8/16, you can comment here and let us know too. @sravanbabuiitm @xiaotinghe @dofuer99 @junrushao1994 @congchan

**Comment by junrushao1994** [comment]
@szha Symbolic beam search #233 is done and have passed unittests. It will be ready to be merged once #264 is done.

**Comment by szha** [comment]
We got text classification based on fasttext thanks to @sravanbabuiitm

**Comment by szha** [comment]
Pinging everyone again. The cutoff is today.

**Comment by szha** [comment]
0.4 has been released. We will track the unfinished items separately.
